#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Mod_SMM_Code

#include "Basic.hpp"

#include "BP_Mod_SMM_Code_classes.hpp"
#include "BP_Mod_SMM_Code_parameters.hpp"


namespace SDK
{

// Function BP_Mod_SMM_Code.BP_Mod_SMM_Code_C.ExecuteUbergraph_BP_Mod_SMM_Code
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Mod_SMM_Code_C::ExecuteUbergraph_BP_Mod_SMM_Code(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mod_SMM_Code_C", "ExecuteUbergraph_BP_Mod_SMM_Code");

	Params::BP_Mod_SMM_Code_C_ExecuteUbergraph_BP_Mod_SMM_Code Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Mod_SMM_Code.BP_Mod_SMM_Code_C.ModDataActiveChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActive                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Mod_SMM_Code_C::ModDataActiveChanged(bool IsActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mod_SMM_Code_C", "ModDataActiveChanged");

	Params::BP_Mod_SMM_Code_C_ModDataActiveChanged Parms{};

	Parms.IsActive = IsActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Mod_SMM_Code.BP_Mod_SMM_Code_C.ModInit
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// TScriptInterface<class IBPI_SBL_Code_C> SimpleModLoader                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Mod_SMM_Code_C::ModInit(TScriptInterface<class IBPI_SBL_Code_C> SimpleModLoader)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mod_SMM_Code_C", "ModInit");

	Params::BP_Mod_SMM_Code_C_ModInit Parms{};

	Parms.SimpleModLoader = SimpleModLoader;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Mod_SMM_Code.BP_Mod_SMM_Code_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Mod_SMM_Code_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mod_SMM_Code_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Mod_SMM_Code.BP_Mod_SMM_Code_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Mod_SMM_Code_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mod_SMM_Code_C", "ReceiveEndPlay");

	Params::BP_Mod_SMM_Code_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}

}

