#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Mod_PlayerLimitEdit

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Mod_PlayerLimitEdit.BP_Mod_PlayerLimitEdit_C.ExecuteUbergraph_BP_Mod_PlayerLimitEdit
// 0x0100 (0x0100 - 0x0000)
struct BP_Mod_PlayerLimitEdit_C_ExecuteUbergraph_BP_Mod_PlayerLimitEdit final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Event_ModName_1;                            // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Event_SlotName_1;                           // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class USMM_SaveGame_Base_C*                   K2Node_Event_SMM_SaveGame_Config;                  // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_SMM_UI_C>         K2Node_Event_SMM_UI;                               // 0x0040(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetIntegerByKey_IntValue;                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIntegerByKey_Valid;                    // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetBoolByKey_BoolValue;                   // 0x0055(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetBoolByKey_Valid;                       // 0x0056(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetPropertyValueAndBroadcast_ReturnValue; // 0x0057(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetCurrentLevelName_ReturnValue;          // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StriStri_ReturnValue;          // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetMaxPlayers_ReturnValue;                // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Event_ModName;                              // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Event_SlotName;                             // 0x00A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class USMM_SaveGame_Base_C*                   K2Node_Event_SMM_SaveGame;                         // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UButton*                                K2Node_Event_Button;                               // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x00C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CA[0x6];                                       // 0x00CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_SBL_Code_C>       K2Node_Event_SimpleModLoader;                      // 0x00D0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsActive;                             // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_SMM_Mod_C>        CallFunc_AsyncRetrieveSG_SMM_Mod_CastInput;        // 0x00E8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBPW_PlayerLimitEditor_UI_C*            CallFunc_Create_ReturnValue;                       // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Mod_PlayerLimitEdit_C_ExecuteUbergraph_BP_Mod_PlayerLimitEdit;

// Function BP_Mod_PlayerLimitEdit.BP_Mod_PlayerLimitEdit_C.ModDataActiveChanged
// 0x0001 (0x0001 - 0x0000)
struct BP_Mod_PlayerLimitEdit_C_ModDataActiveChanged final
{
public:
	bool                                          IsActive;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Mod_PlayerLimitEdit_C_ModDataActiveChanged;

// Function BP_Mod_PlayerLimitEdit.BP_Mod_PlayerLimitEdit_C.ModInit
// 0x0010 (0x0010 - 0x0000)
struct BP_Mod_PlayerLimitEdit_C_ModInit final
{
public:
	TScriptInterface<class IBPI_SBL_Code_C>       SimpleModLoader;                                   // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Mod_PlayerLimitEdit_C_ModInit;

// Function BP_Mod_PlayerLimitEdit.BP_Mod_PlayerLimitEdit_C.ModMenuPostInit
// 0x0010 (0x0010 - 0x0000)
struct BP_Mod_PlayerLimitEdit_C_ModMenuPostInit final
{
public:
	TScriptInterface<class IBPI_SMM_UI_C>         SMM_UI;                                            // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Mod_PlayerLimitEdit_C_ModMenuPostInit;

// Function BP_Mod_PlayerLimitEdit.BP_Mod_PlayerLimitEdit_C.OnRetrievedSG
// 0x0028 (0x0028 - 0x0000)
struct BP_Mod_PlayerLimitEdit_C_OnRetrievedSG final
{
public:
	class FString                                 ModName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 SlotName;                                          // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class USMM_SaveGame_Base_C*                   SMM_SaveGame_Config;                               // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Mod_PlayerLimitEdit_C_OnRetrievedSG;

// Function BP_Mod_PlayerLimitEdit.BP_Mod_PlayerLimitEdit_C.OnSavedSG
// 0x0028 (0x0028 - 0x0000)
struct BP_Mod_PlayerLimitEdit_C_OnSavedSG final
{
public:
	class FString                                 ModName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 SlotName;                                          // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class USMM_SaveGame_Base_C*                   SMM_SaveGame;                                      // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Mod_PlayerLimitEdit_C_OnSavedSG;

// Function BP_Mod_PlayerLimitEdit.BP_Mod_PlayerLimitEdit_C.SendTabButton
// 0x0008 (0x0008 - 0x0000)
struct BP_Mod_PlayerLimitEdit_C_SendTabButton final
{
public:
	class UButton*                                Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Mod_PlayerLimitEdit_C_SendTabButton;

// Function BP_Mod_PlayerLimitEdit.BP_Mod_PlayerLimitEdit_C.SetNavigationFocus
// 0x0008 (0x0008 - 0x0000)
struct BP_Mod_PlayerLimitEdit_C_SetNavigationFocus final
{
public:
	class UWidget*                                Widget;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Mod_PlayerLimitEdit_C_SetNavigationFocus;

}

