#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Mod_PlayerLimitEdit

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Mod_PlayerLimitEdit.BP_Mod_PlayerLimitEdit_C
// 0x0040 (0x02E0 - 0x02A0)
class ABP_Mod_PlayerLimitEdit_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_SMM_UI_C>         SMMui;                                             // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SMMLoaded;                                         // 0x02C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C1[0x3];                                      // 0x02C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MaxPlayers;                                        // 0x02C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Override;                                          // 0x02C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C9[0x7];                                      // 0x02C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AReadyOrNotPlayerController*            RonController;                                     // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UBPW_PlayerLimitEditor_UI_C*            PLE_UI;                                            // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Mod_PlayerLimitEdit(int32 EntryPoint);
	void LogUpdated();
	void Loop();
	void ModDataActiveChanged(bool IsActive);
	void ModInit(TScriptInterface<class IBPI_SBL_Code_C> SimpleModLoader);
	void ModMenuPostInit(const TScriptInterface<class IBPI_SMM_UI_C> SMM_UI);
	void OnRetrievedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame_Config);
	void OnSavedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame);
	void OnUpdated_Event();
	void PageClosed();
	void PageOpened();
	void ReceiveBeginPlay();
	void SendTabButton(class UButton* Button);
	void SetNavigationFocus(class UWidget** Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Mod_PlayerLimitEdit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Mod_PlayerLimitEdit_C")
	}
	static class ABP_Mod_PlayerLimitEdit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Mod_PlayerLimitEdit_C>();
	}
};
DUMPER7_ASSERTS_ABP_Mod_PlayerLimitEdit_C;

}

