#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_SMM_Mod

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_SMM_Mod.BPI_SMM_Mod_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_SMM_Mod_C final
{
public:
	void LogUpdated();
	void ModMenuPostInit(const TScriptInterface<class IBPI_SMM_UI_C> SMM_UI);
	void OnRetrievedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame_Config);
	void OnSavedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame);
	void PageClosed();
	void PageOpened();
	void SendTabButton(class UButton* Button);
	void SetNavigationFocus(class UWidget** Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_SMM_Mod_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_SMM_Mod_C")
	}
	static class IBPI_SMM_Mod_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_SMM_Mod_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_SMM_Mod_C;

}

