#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_SMM_Mod

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPI_SMM_Mod.BPI_SMM_Mod_C.ModMenuPostInit
// 0x0010 (0x0010 - 0x0000)
struct BPI_SMM_Mod_C_ModMenuPostInit final
{
public:
	TScriptInterface<class IBPI_SMM_UI_C>         SMM_UI;                                            // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_SMM_Mod_C_ModMenuPostInit;

// Function BPI_SMM_Mod.BPI_SMM_Mod_C.OnRetrievedSG
// 0x0028 (0x0028 - 0x0000)
struct BPI_SMM_Mod_C_OnRetrievedSG final
{
public:
	class FString                                 ModName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 SlotName;                                          // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class USMM_SaveGame_Base_C*                   SMM_SaveGame_Config;                               // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_SMM_Mod_C_OnRetrievedSG;

// Function BPI_SMM_Mod.BPI_SMM_Mod_C.OnSavedSG
// 0x0028 (0x0028 - 0x0000)
struct BPI_SMM_Mod_C_OnSavedSG final
{
public:
	class FString                                 ModName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 SlotName;                                          // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class USMM_SaveGame_Base_C*                   SMM_SaveGame;                                      // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_SMM_Mod_C_OnSavedSG;

// Function BPI_SMM_Mod.BPI_SMM_Mod_C.SendTabButton
// 0x0008 (0x0008 - 0x0000)
struct BPI_SMM_Mod_C_SendTabButton final
{
public:
	class UButton*                                Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_SMM_Mod_C_SendTabButton;

// Function BPI_SMM_Mod.BPI_SMM_Mod_C.SetNavigationFocus
// 0x0008 (0x0008 - 0x0000)
struct BPI_SMM_Mod_C_SetNavigationFocus final
{
public:
	class UWidget*                                Widget;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_SMM_Mod_C_SetNavigationFocus;

}

