#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS_SMM_SettingPageInfo

#include "Basic.hpp"

#include "BPS_SMM_PageInfo_structs.hpp"


namespace SDK
{

// UserDefinedStruct BPS_SMM_SettingPageInfo.BPS_SMM_SettingPageInfo
// 0x0038 (0x0038 - 0x0000)
struct FBPS_SMM_SettingPageInfo final
{
public:
	class FText                                   TabDisplayName_11_981D01E248F5288CF2577EA689DDFD6E; // 0x0000(0x0018)(Edit, BlueprintVisible)
	class FName                                   TabKey_19_1F0F64EC46389417E998F582AA34E570;        // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FBPS_SMM_PageInfo>              Widgets_18_F921835A496F62695715F6AC91936C54;       // 0x0020(0x0010)(Edit, BlueprintVisible)
	int32                                         TabOrder_22_13B9DB61450474C2C12D14BC1E2E5458;      // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FBPS_SMM_SettingPageInfo;

}

