#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS_SMM_PageInfo

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct BPS_SMM_PageInfo.BPS_SMM_PageInfo
// 0x0050 (0x0050 - 0x0000)
struct FBPS_SMM_PageInfo final
{
public:
	class FText                                   TabDisplayName_11_981D01E248F5288CF2577EA689DDFD6E; // 0x0000(0x0018)(Edit, BlueprintVisible)
	class FName                                   TabKey_17_1F0F64EC46389417E998F582AA34E570;        // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   Widget_16_F921835A496F62695715F6AC91936C54;        // 0x0020(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          DeferLoad_19_2A69DE0D4EBC4124A2EBF78343451EB5;     // 0x0048(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TabOrder_25_A3C432C84AFFA2A3060345A3D4E1710E;      // 0x004C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FBPS_SMM_PageInfo;

}

