#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS_SMM_SaveQueue

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct BPS_SMM_SaveQueue.BPS_SMM_SaveQueue
// 0x0010 (0x0010 - 0x0000)
struct FBPS_SMM_SaveQueue final
{
public:
	TArray<TScriptInterface<class IBPI_SMM_Mod_C>> SMMMods_3_56A9C7A34D99436C939D2FB1B2492E1A;       // 0x0000(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FBPS_SMM_SaveQueue;

}

