#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS_SBL_SaveGame

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPS_SBL_SaveGame.BPS_SBL_SaveGame_C
// 0x0008 (0x0030 - 0x0028)
class UBPS_SBL_SaveGame_C final : public USaveGame
{
public:
	bool                                          Active;                                            // 0x0028(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPS_SBL_SaveGame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPS_SBL_SaveGame_C")
	}
	static class UBPS_SBL_SaveGame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPS_SBL_SaveGame_C>();
	}
};
DUMPER7_ASSERTS_UBPS_SBL_SaveGame_C;

}

