#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_LevelSelector_LevelButton

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "ReadyOrNot_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_SMM_LevelSelector_LevelButton.BPW_SMM_LevelSelector_LevelButton_C
// 0x1138 (0x1400 - 0x02C8)
class UBPW_SMM_LevelSelector_LevelButton_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_ActiveFlair;                                // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_KeyboardFocus;                              // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button;                                            // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_Title;                                // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLevelDataLookupTable                  LevelData;                                         // 0x02F0(0x08D0)(Edit, BlueprintVisible, ExposeOnSpawn)
	TMulticastInlineDelegate<void(class UBPW_SMM_LevelSelector_LevelButton_C* LevelButton)> OnSelectedLevel; // 0x0BC0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FString                                 LevelName;                                         // 0x0BD0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          State;                                             // 0x0BE0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BE1[0xF];                                      // 0x0BE1(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonStyle                           FalseStyle;                                        // 0x0BF0(0x03F0)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FButtonStyle                           TrueStyle;                                         // 0x0FE0(0x03F0)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UObject_SMM_LevelSelector_EntryPoint_C*> EntryPoints;                               // 0x13D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   DisplayName;                                       // 0x13E0(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          modded;                                            // 0x13F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void BndEvt__BPW_SMM_LevelSelector_LevelButton_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_LevelSelector_LevelButton_Button_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_LevelSelector_LevelButton_Button_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_BPW_SMM_LevelSelector_LevelButton(int32 EntryPoint);
	void HideFocus();
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnRep_State();
	void PreConstruct(bool IsDesignTime);
	void UpdateButtonVisuals(bool Selected);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_SMM_LevelSelector_LevelButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_SMM_LevelSelector_LevelButton_C")
	}
	static class UBPW_SMM_LevelSelector_LevelButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_SMM_LevelSelector_LevelButton_C>();
	}
};
DUMPER7_ASSERTS_UBPW_SMM_LevelSelector_LevelButton_C;

}

