#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_Tab_Small

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function BPW_SMM_Tab_Small.BPW_SMM_Tab_Small_C.ExecuteUbergraph_BPW_SMM_Tab_Small
// 0x0068 (0x0068 - 0x0000)
struct BPW_SMM_Tab_Small_C_ExecuteUbergraph_BPW_SMM_Tab_Small final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateFontInfo                         CallFunc_GetFont_ReturnValue;                      // 0x0008(0x0058)(ConstParm, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPW_SMM_Tab_Small_C_ExecuteUbergraph_BPW_SMM_Tab_Small;

// Function BPW_SMM_Tab_Small.BPW_SMM_Tab_Small_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct BPW_SMM_Tab_Small_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPW_SMM_Tab_Small_C_PreConstruct;

}

