#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_ConfigSMM

#include "Basic.hpp"

#include "BPW_ConfigSMM_classes.hpp"
#include "BPW_ConfigSMM_parameters.hpp"


namespace SDK
{

// Function BPW_ConfigSMM.BPW_ConfigSMM_C.SetNavigationFocus
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget**                         Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPW_ConfigSMM_C::SetNavigationFocus(class UWidget** Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_ConfigSMM_C", "SetNavigationFocus");

	Params::BPW_ConfigSMM_C_SetNavigationFocus Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}

}

