#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_Tab_Small

#include "Basic.hpp"

#include "BPW_SMM_Tab_Small_classes.hpp"
#include "BPW_SMM_Tab_Small_parameters.hpp"


namespace SDK
{

// Function BPW_SMM_Tab_Small.BPW_SMM_Tab_Small_C.ExecuteUbergraph_BPW_SMM_Tab_Small
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Tab_Small_C::ExecuteUbergraph_BPW_SMM_Tab_Small(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Tab_Small_C", "ExecuteUbergraph_BPW_SMM_Tab_Small");

	Params::BPW_SMM_Tab_Small_C_ExecuteUbergraph_BPW_SMM_Tab_Small Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Tab_Small.BPW_SMM_Tab_Small_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Tab_Small_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Tab_Small_C", "PreConstruct");

	Params::BPW_SMM_Tab_Small_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

