#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_Settings_Pages_Container

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_SMM_Settings_Pages_Container.BPW_SMM_Settings_Pages_Container_C
// 0x0090 (0x0358 - 0x02C8)
class UBPW_SMM_Settings_Pages_Container_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UScrollBox*                             ScrollBox_PageTabs;                                // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_106;                                // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBPW_SMM_TabSetting_C*                  SettingTab;                                        // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UBPW_SMM_Tab_C*                         SelectedTabWidget;                                 // 0x02E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   SelectedTabKey;                                    // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_SMM_UI_C>         SMM_UI;                                            // 0x02F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMap<class FName, class UUserWidget*>         Tabs;                                              // 0x0308(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	class UWidget* DoCustomNavigation(EUINavigation Navigation_0);
	void ExecuteUbergraph_BPW_SMM_Settings_Pages_Container(int32 EntryPoint);
	void InitilizePageTabs();
	void Localize(const class FText& InText, class FText* OutText);
	void PreConstruct(bool IsDesignTime);
	void SmallTabSelected_Event(class UBPW_SMM_Tab_C* TabWidget);
	void WidgetCreated_Event(class UBPW_SMM_Tab_C* Tab);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_SMM_Settings_Pages_Container_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_SMM_Settings_Pages_Container_C")
	}
	static class UBPW_SMM_Settings_Pages_Container_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_SMM_Settings_Pages_Container_C>();
	}
};
DUMPER7_ASSERTS_UBPW_SMM_Settings_Pages_Container_C;

}

