#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_TopButton_MissionSelect

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C
// 0x0020 (0x02E8 - 0x02C8)
class UBPW_TopButton_MissionSelect_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_Customize;                                  // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TScriptInterface<class IBPI_SMM_UI_C>         SMM_UI;                                            // 0x02D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BPW_TopButton_Customize_Button_Customize_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void ExecuteUbergraph_BPW_TopButton_MissionSelect(int32 EntryPoint);
	void LogUpdated();
	void ModMenuPostInit(const TScriptInterface<class IBPI_SMM_UI_C> SMM_UI_0);
	void OnRetrievedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame_Config);
	void OnSavedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame);
	void OpenMissions(bool* Continue);
	void PageClosed();
	void PageOpened();
	void SendTabButton(class UButton* Button);
	void SetNavigationFocus(class UWidget** Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_TopButton_MissionSelect_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_TopButton_MissionSelect_C")
	}
	static class UBPW_TopButton_MissionSelect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_TopButton_MissionSelect_C>();
	}
};
DUMPER7_ASSERTS_UBPW_TopButton_MissionSelect_C;

}

