#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_ConfigPLE

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPW_ConfigPLE.BPW_ConfigPLE_C.SetNavigationFocus
// 0x0008 (0x0008 - 0x0000)
struct BPW_ConfigPLE_C_SetNavigationFocus final
{
public:
	class UWidget*                                Widget;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPW_ConfigPLE_C_SetNavigationFocus;

}

