#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_PlayerLimitEditor_UI

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_PlayerLimitEditor_UI.BPW_PlayerLimitEditor_UI_C
// 0x0030 (0x02F8 - 0x02C8)
class UBPW_PlayerLimitEditor_UI_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_Refresh;                                    // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_SetLimit;                                   // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       CommonTextBlock_SetButtonText;                     // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       CommonTextBlock_Status;                            // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         NewLimitValue;                                     // 0x02F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NetMaxPlayers;                                     // 0x02F4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BPW_PlayerLimitEditor_UI_Button_Refresh_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__BPW_PlayerLimitEditor_UI_Button_SetLimit_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_BPW_PlayerLimitEditor_UI(int32 EntryPoint);
	void NewLimitValueUpdated(class UObject* Object, const struct FFieldNotificationId& Field);
	void PreConstruct(bool IsDesignTime);
	void UpdateStatusText();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_PlayerLimitEditor_UI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_PlayerLimitEditor_UI_C")
	}
	static class UBPW_PlayerLimitEditor_UI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_PlayerLimitEditor_UI_C>();
	}
};
DUMPER7_ASSERTS_UBPW_PlayerLimitEditor_UI_C;

}

