#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_ModEntry

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_SMM_ModEntry.BPW_SMM_ModEntry_C
// 0x0080 (0x0348 - 0x02C8)
class UBPW_SMM_ModEntry_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBPW_ToggleButton_C*                    BPW_ToggleButton;                                  // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Main;                                       // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_DisplayTitle;                         // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_Focus;                                // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   DisplayTitle;                                      // 0x02F0(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          Enabled;                                           // 0x0308(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_309[0x7];                                      // 0x0309(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPDA_SBL_ModData_C*                     SBLdata;                                           // 0x0310(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UBPW_SMM_ModEntry_C* Widget)> OnSelected;                    // 0x0318(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Value, class UBPW_SMM_ModEntry_C* Widget)> OnStateChanged;    // 0x0328(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(EUINavigation Direction)> CalledNavigation;                        // 0x0338(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__BPW_SMM_ModEntry_BPW_ToggleButton_K2Node_ComponentBoundEvent_0_OnBoolChanged__DelegateSignature(bool Value);
	void BndEvt__BPW_SMM_ModEntry_BPW_ToggleButton_K2Node_ComponentBoundEvent_6_AddedToFocusPath__DelegateSignature();
	void BndEvt__BPW_SMM_ModEntry_Button_Main_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_ModEntry_Button_Main_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_ModEntry_Button_Main_K2Node_ComponentBoundEvent_5_OnButtonReleasedEvent__DelegateSignature();
	void Construct();
	class UWidget* DoCustomNavigation(EUINavigation Navigation_0);
	class UWidget* DoCustomNavigation_0(EUINavigation Navigation_0);
	void ExecuteUbergraph_BPW_SMM_ModEntry(int32 EntryPoint);
	void HideFocus();
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);
	void PreConstruct(bool IsDesignTime);
	void ShowFocus();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_SMM_ModEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_SMM_ModEntry_C")
	}
	static class UBPW_SMM_ModEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_SMM_ModEntry_C>();
	}
};
DUMPER7_ASSERTS_UBPW_SMM_ModEntry_C;

}

