#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_TopButton_MissionSelect

#include "Basic.hpp"

#include "BPW_TopButton_MissionSelect_classes.hpp"
#include "BPW_TopButton_MissionSelect_parameters.hpp"


namespace SDK
{

// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.BndEvt__BPW_TopButton_Customize_Button_Customize_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBPW_TopButton_MissionSelect_C::BndEvt__BPW_TopButton_Customize_Button_Customize_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "BndEvt__BPW_TopButton_Customize_Button_Customize_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.ExecuteUbergraph_BPW_TopButton_MissionSelect
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_TopButton_MissionSelect_C::ExecuteUbergraph_BPW_TopButton_MissionSelect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "ExecuteUbergraph_BPW_TopButton_MissionSelect");

	Params::BPW_TopButton_MissionSelect_C_ExecuteUbergraph_BPW_TopButton_MissionSelect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.LogUpdated
// (Public, BlueprintCallable, BlueprintEvent)

void UBPW_TopButton_MissionSelect_C::LogUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "LogUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.ModMenuPostInit
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TScriptInterface<class IBPI_SMM_UI_C>SMM_UI_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_TopButton_MissionSelect_C::ModMenuPostInit(const TScriptInterface<class IBPI_SMM_UI_C> SMM_UI_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "ModMenuPostInit");

	Params::BPW_TopButton_MissionSelect_C_ModMenuPostInit Parms{};

	Parms.SMM_UI_0 = SMM_UI_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.OnRetrievedSG
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ModName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    SlotName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class USMM_SaveGame_Base_C*             SMM_SaveGame_Config                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPW_TopButton_MissionSelect_C::OnRetrievedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame_Config)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "OnRetrievedSG");

	Params::BPW_TopButton_MissionSelect_C_OnRetrievedSG Parms{};

	Parms.ModName = std::move(ModName);
	Parms.SlotName = std::move(SlotName);
	Parms.SMM_SaveGame_Config = SMM_SaveGame_Config;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.OnSavedSG
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ModName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    SlotName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class USMM_SaveGame_Base_C*             SMM_SaveGame                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPW_TopButton_MissionSelect_C::OnSavedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "OnSavedSG");

	Params::BPW_TopButton_MissionSelect_C_OnSavedSG Parms{};

	Parms.ModName = std::move(ModName);
	Parms.SlotName = std::move(SlotName);
	Parms.SMM_SaveGame = SMM_SaveGame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.OpenMissions
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Continue                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_TopButton_MissionSelect_C::OpenMissions(bool* Continue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "OpenMissions");

	Params::BPW_TopButton_MissionSelect_C_OpenMissions Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Continue != nullptr)
		*Continue = Parms.Continue;
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.PageClosed
// (Public, BlueprintCallable, BlueprintEvent)

void UBPW_TopButton_MissionSelect_C::PageClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "PageClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.PageOpened
// (Public, BlueprintCallable, BlueprintEvent)

void UBPW_TopButton_MissionSelect_C::PageOpened()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "PageOpened");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.SendTabButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UButton*                          Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPW_TopButton_MissionSelect_C::SendTabButton(class UButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "SendTabButton");

	Params::BPW_TopButton_MissionSelect_C_SendTabButton Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_TopButton_MissionSelect.BPW_TopButton_MissionSelect_C.SetNavigationFocus
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget**                         Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPW_TopButton_MissionSelect_C::SetNavigationFocus(class UWidget** Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_TopButton_MissionSelect_C", "SetNavigationFocus");

	Params::BPW_TopButton_MissionSelect_C_SetNavigationFocus Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}

}

