#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_Tab_Small

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BPW_SMM_Tab_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_SMM_Tab_Small.BPW_SMM_Tab_Small_C
// 0x0010 (0x0BB0 - 0x0BA0)
class UBPW_SMM_Tab_Small_C final : public UBPW_SMM_Tab_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BPW_SMM_Tab_Small_C;                // 0x0BA0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BPW_SMM_Tab_Small(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_SMM_Tab_Small_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_SMM_Tab_Small_C")
	}
	static class UBPW_SMM_Tab_Small_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_SMM_Tab_Small_C>();
	}
};
DUMPER7_ASSERTS_UBPW_SMM_Tab_Small_C;

}

