#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_LevelSelector_EntryPoint

#include "Basic.hpp"

#include "BPW_SMM_LevelSelector_EntryPoint_classes.hpp"
#include "BPW_SMM_LevelSelector_EntryPoint_parameters.hpp"


namespace SDK
{

// Function BPW_SMM_LevelSelector_EntryPoint.BPW_SMM_LevelSelector_EntryPoint_C.BndEvt__BPW_SMM_LevelSelector_EntryPoint_Button_EntryPoint_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBPW_SMM_LevelSelector_EntryPoint_C::BndEvt__BPW_SMM_LevelSelector_EntryPoint_Button_EntryPoint_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_EntryPoint_C", "BndEvt__BPW_SMM_LevelSelector_EntryPoint_Button_EntryPoint_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_LevelSelector_EntryPoint.BPW_SMM_LevelSelector_EntryPoint_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UBPW_SMM_LevelSelector_EntryPoint_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_EntryPoint_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_LevelSelector_EntryPoint.BPW_SMM_LevelSelector_EntryPoint_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_LevelSelector_EntryPoint_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_EntryPoint_C", "BP_OnItemExpansionChanged");

	Params::BPW_SMM_LevelSelector_EntryPoint_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_LevelSelector_EntryPoint.BPW_SMM_LevelSelector_EntryPoint_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_LevelSelector_EntryPoint_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_EntryPoint_C", "BP_OnItemSelectionChanged");

	Params::BPW_SMM_LevelSelector_EntryPoint_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_LevelSelector_EntryPoint.BPW_SMM_LevelSelector_EntryPoint_C.ExecuteUbergraph_BPW_SMM_LevelSelector_EntryPoint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_LevelSelector_EntryPoint_C::ExecuteUbergraph_BPW_SMM_LevelSelector_EntryPoint(int32 EntryPoint_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_EntryPoint_C", "ExecuteUbergraph_BPW_SMM_LevelSelector_EntryPoint");

	Params::BPW_SMM_LevelSelector_EntryPoint_C_ExecuteUbergraph_BPW_SMM_LevelSelector_EntryPoint Parms{};

	Parms.EntryPoint_0 = EntryPoint_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_LevelSelector_EntryPoint.BPW_SMM_LevelSelector_EntryPoint_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_LevelSelector_EntryPoint_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_EntryPoint_C", "OnListItemObjectSet");

	Params::BPW_SMM_LevelSelector_EntryPoint_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_LevelSelector_EntryPoint.BPW_SMM_LevelSelector_EntryPoint_C.OnRep_Selected
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void UBPW_SMM_LevelSelector_EntryPoint_C::OnRep_Selected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_EntryPoint_C", "OnRep_Selected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_LevelSelector_EntryPoint.BPW_SMM_LevelSelector_EntryPoint_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_LevelSelector_EntryPoint_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_EntryPoint_C", "PreConstruct");

	Params::BPW_SMM_LevelSelector_EntryPoint_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_LevelSelector_EntryPoint.BPW_SMM_LevelSelector_EntryPoint_C.SetWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// TSoftObjectPtr<class UTexture2D>        InputPin                                               (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBPW_SMM_LevelSelector_EntryPoint_C::SetWidget(const class FText& InText, TSoftObjectPtr<class UTexture2D> InputPin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_EntryPoint_C", "SetWidget");

	Params::BPW_SMM_LevelSelector_EntryPoint_C_SetWidget Parms{};

	Parms.InText = std::move(InText);
	Parms.InputPin = InputPin;

	UObject::ProcessEvent(Func, &Parms);
}

}

