#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_TabSetting

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "BPS_SMM_PageInfo_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_SMM_TabSetting.BPW_SMM_TabSetting_C
// 0x0868 (0x0B30 - 0x02C8)
class UBPW_SMM_TabSetting_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_ActiveFlair;                                // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_KeyboardFocus;                              // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Tab;                                        // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_Title;                                // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   TabDisplayName;                                    // 0x02F0(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FName                                   TabKey;                                            // 0x0308(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TArray<struct FBPS_SMM_PageInfo>              Pages;                                             // 0x0310(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	TMulticastInlineDelegate<void(class UBPW_SMM_TabSetting_C* SettingTabWidget, bool Keyboard)> SettingTabSelected; // 0x0320(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         SortOrder;                                         // 0x0330(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          TabState;                                          // 0x0334(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          NewVar;                                            // 0x0335(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_336[0xA];                                      // 0x0336(0x000A)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonStyle                           StyleFalse;                                        // 0x0340(0x03F0)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FButtonStyle                           StyleTrue;                                         // 0x0730(0x03F0)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UBPW_SMM_Settings_Pages_Container_C*    Container;                                         // 0x0B20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BPW_SMM_Tab_Button_Tab_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_Tab_Button_Tab_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_TabSetting_Button_Tab_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void CreateContainer(class UWidgetSwitcher* WidgetSwitcher, TScriptInterface<class IBPI_SMM_UI_C> SMM_UI);
	class UWidget* DoCustomNavigation(EUINavigation Navigation_0);
	void ExecuteUbergraph_BPW_SMM_TabSetting(int32 EntryPoint);
	void HideFocus();
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnRep_TabState();
	void PreConstruct(bool IsDesignTime);
	void UpdateTabVisuals(bool Selected);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_SMM_TabSetting_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_SMM_TabSetting_C")
	}
	static class UBPW_SMM_TabSetting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_SMM_TabSetting_C>();
	}
};
DUMPER7_ASSERTS_UBPW_SMM_TabSetting_C;

}

