#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_LevelSelector_CampaignButton

#include "Basic.hpp"

#include "BPW_SMM_LevelSelector_CampaignButton_classes.hpp"
#include "BPW_SMM_LevelSelector_CampaignButton_parameters.hpp"


namespace SDK
{

// Function BPW_SMM_LevelSelector_CampaignButton.BPW_SMM_LevelSelector_CampaignButton_C.BndEvt__BPW_SMM_LevelSelector_CampaignButton_Button_ReadyOrNot_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBPW_SMM_LevelSelector_CampaignButton_C::BndEvt__BPW_SMM_LevelSelector_CampaignButton_Button_ReadyOrNot_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_CampaignButton_C", "BndEvt__BPW_SMM_LevelSelector_CampaignButton_Button_ReadyOrNot_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_LevelSelector_CampaignButton.BPW_SMM_LevelSelector_CampaignButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPW_SMM_LevelSelector_CampaignButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_CampaignButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_LevelSelector_CampaignButton.BPW_SMM_LevelSelector_CampaignButton_C.ExecuteUbergraph_BPW_SMM_LevelSelector_CampaignButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_LevelSelector_CampaignButton_C::ExecuteUbergraph_BPW_SMM_LevelSelector_CampaignButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_CampaignButton_C", "ExecuteUbergraph_BPW_SMM_LevelSelector_CampaignButton");

	Params::BPW_SMM_LevelSelector_CampaignButton_C_ExecuteUbergraph_BPW_SMM_LevelSelector_CampaignButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_LevelSelector_CampaignButton.BPW_SMM_LevelSelector_CampaignButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_LevelSelector_CampaignButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_LevelSelector_CampaignButton_C", "PreConstruct");

	Params::BPW_SMM_LevelSelector_CampaignButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

