#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_LevelSelector_LevelButton

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function BPW_SMM_LevelSelector_LevelButton.BPW_SMM_LevelSelector_LevelButton_C.ExecuteUbergraph_BPW_SMM_LevelSelector_LevelButton
// 0x0440 (0x0440 - 0x0000)
struct BPW_SMM_LevelSelector_LevelButton_C_ExecuteUbergraph_BPW_SMM_LevelSelector_LevelButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0008(0x0018)()
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable; // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Selected;                       // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0xB];                                       // 0x0025(0x000B)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonStyle                           K2Node_Select_Default;                             // 0x0030(0x03F0)(ConstParm)
	struct FFocusEvent                            K2Node_Event_InFocusEvent_1;                       // 0x0420(0x0008)(NoDestructor)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x0428(0x0008)(NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0430(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPW_SMM_LevelSelector_LevelButton_C_ExecuteUbergraph_BPW_SMM_LevelSelector_LevelButton;

// Function BPW_SMM_LevelSelector_LevelButton.BPW_SMM_LevelSelector_LevelButton_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct BPW_SMM_LevelSelector_LevelButton_C_OnAddedToFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
DUMPER7_ASSERTS_BPW_SMM_LevelSelector_LevelButton_C_OnAddedToFocusPath;

// Function BPW_SMM_LevelSelector_LevelButton.BPW_SMM_LevelSelector_LevelButton_C.OnRemovedFromFocusPath
// 0x0008 (0x0008 - 0x0000)
struct BPW_SMM_LevelSelector_LevelButton_C_OnRemovedFromFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
DUMPER7_ASSERTS_BPW_SMM_LevelSelector_LevelButton_C_OnRemovedFromFocusPath;

// Function BPW_SMM_LevelSelector_LevelButton.BPW_SMM_LevelSelector_LevelButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct BPW_SMM_LevelSelector_LevelButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPW_SMM_LevelSelector_LevelButton_C_PreConstruct;

// Function BPW_SMM_LevelSelector_LevelButton.BPW_SMM_LevelSelector_LevelButton_C.UpdateButtonVisuals
// 0x0001 (0x0001 - 0x0000)
struct BPW_SMM_LevelSelector_LevelButton_C_UpdateButtonVisuals final
{
public:
	bool                                          Selected;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPW_SMM_LevelSelector_LevelButton_C_UpdateButtonVisuals;

}

