#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_Tab

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "BPS_SMM_PageInfo_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_SMM_Tab.BPW_SMM_Tab_C
// 0x08D8 (0x0BA0 - 0x02C8)
class UBPW_SMM_Tab_C : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_ActiveFlair;                                // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_KeyboardFocus;                              // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Tab;                                        // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_Title;                                // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_0;                                         // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   TabDisplayName;                                    // 0x02F8(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FName                                   TabKey;                                            // 0x0310(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UUserWidget*                            WidgetObject;                                      // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   WidgetClass;                                       // 0x0320(0x0028)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UBPW_SMM_Tab_C* TabWidget)> TabSelected;                     // 0x0348(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          TabState;                                          // 0x0358(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_359[0x7];                                      // 0x0359(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonStyle                           TrueStyle;                                         // 0x0360(0x03F0)(Edit, BlueprintVisible)
	struct FButtonStyle                           FalseStyle;                                        // 0x0750(0x03F0)(Edit, BlueprintVisible)
	struct FBPS_SMM_PageInfo                      PageInfo;                                          // 0x0B40(0x0050)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UBPW_SMM_Tab_C* Tab)> WidgetCreated;                         // 0x0B90(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__BPW_SMM_Tab_Button_Tab_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_Tab_Button_Tab_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_Tab_Button_Tab_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature();
	void ExecuteUbergraph_BPW_SMM_Tab(int32 EntryPoint);
	void HideFocus();
	void LoadAndCreateWidgetClass(class UWidgetSwitcher* WidgetSwitcher, TScriptInterface<class IBPI_SMM_UI_C> SMM_UI, bool isConfig);
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnLoaded_2E2CCC9F4172B3383914AD806CEBAE03(TSubclassOf<class UObject> Loaded);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnRep_TabState();
	void PreConstruct(bool IsDesignTime);
	void UpdateTabVisuals(bool Selected);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_SMM_Tab_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_SMM_Tab_C")
	}
	static class UBPW_SMM_Tab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_SMM_Tab_C>();
	}
};
DUMPER7_ASSERTS_UBPW_SMM_Tab_C;

}

