#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_Settings_Pages_Container

#include "Basic.hpp"

#include "BPW_SMM_Settings_Pages_Container_classes.hpp"
#include "BPW_SMM_Settings_Pages_Container_parameters.hpp"


namespace SDK
{

// Function BPW_SMM_Settings_Pages_Container.BPW_SMM_Settings_Pages_Container_C.DoCustomNavigation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UBPW_SMM_Settings_Pages_Container_C::DoCustomNavigation(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Settings_Pages_Container_C", "DoCustomNavigation");

	Params::BPW_SMM_Settings_Pages_Container_C_DoCustomNavigation Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BPW_SMM_Settings_Pages_Container.BPW_SMM_Settings_Pages_Container_C.ExecuteUbergraph_BPW_SMM_Settings_Pages_Container
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Settings_Pages_Container_C::ExecuteUbergraph_BPW_SMM_Settings_Pages_Container(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Settings_Pages_Container_C", "ExecuteUbergraph_BPW_SMM_Settings_Pages_Container");

	Params::BPW_SMM_Settings_Pages_Container_C_ExecuteUbergraph_BPW_SMM_Settings_Pages_Container Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Settings_Pages_Container.BPW_SMM_Settings_Pages_Container_C.InitilizePageTabs
// (BlueprintCallable, BlueprintEvent)

void UBPW_SMM_Settings_Pages_Container_C::InitilizePageTabs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Settings_Pages_Container_C", "InitilizePageTabs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_Settings_Pages_Container.BPW_SMM_Settings_Pages_Container_C.Localize
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText*                            OutText                                                (Parm, OutParm)

void UBPW_SMM_Settings_Pages_Container_C::Localize(const class FText& InText, class FText* OutText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Settings_Pages_Container_C", "Localize");

	Params::BPW_SMM_Settings_Pages_Container_C_Localize Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);

	if (OutText != nullptr)
		*OutText = std::move(Parms.OutText);
}


// Function BPW_SMM_Settings_Pages_Container.BPW_SMM_Settings_Pages_Container_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Settings_Pages_Container_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Settings_Pages_Container_C", "PreConstruct");

	Params::BPW_SMM_Settings_Pages_Container_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Settings_Pages_Container.BPW_SMM_Settings_Pages_Container_C.SmallTabSelected_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBPW_SMM_Tab_C*                   TabWidget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Settings_Pages_Container_C::SmallTabSelected_Event(class UBPW_SMM_Tab_C* TabWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Settings_Pages_Container_C", "SmallTabSelected_Event");

	Params::BPW_SMM_Settings_Pages_Container_C_SmallTabSelected_Event Parms{};

	Parms.TabWidget = TabWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Settings_Pages_Container.BPW_SMM_Settings_Pages_Container_C.WidgetCreated_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBPW_SMM_Tab_C*                   Tab                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Settings_Pages_Container_C::WidgetCreated_Event(class UBPW_SMM_Tab_C* Tab)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Settings_Pages_Container_C", "WidgetCreated_Event");

	Params::BPW_SMM_Settings_Pages_Container_C_WidgetCreated_Event Parms{};

	Parms.Tab = Tab;

	UObject::ProcessEvent(Func, &Parms);
}

}

