#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_Page_LevelSelector

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "ReadyOrNot_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_SMM_Page_LevelSelector.BPW_SMM_Page_LevelSelector_C
// 0x0170 (0x0438 - 0x02C8)
class UBPW_SMM_Page_LevelSelector_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_Refresh;                                    // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_StartMission;                               // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        ComboBoxString_Difficulty;                         // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_Difficulty;                           // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_LevelDesignation;                     // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_LevelNickName;                        // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_StartButtonText;                      // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_urllabel;                             // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       EditableTextBox_URL_Entrypoint;                    // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       EditableTextBox_URL_Gamemode;                      // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       EditableTextBox_URL_Level;                         // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_URLrow;                              // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_LevelPicture;                                // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UListView*                              ListView_EntryPoints;                              // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMultiLineEditableText*                 MultiLineEditableText_Description;                 // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        Switcher_Levels;                                   // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWrapBox*                               WrapBox_Campaigns;                                 // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TSoftObjectPtr<class UDataTable>              LevelDataTable;                                    // 0x0358(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UBPW_SMM_LevelSelector_LevelButton_C*   SelectedLevel;                                     // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_SMM_UI_C>         SMM_UI;                                            // 0x0388(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USMM_SaveGame_Config_SMM_C*             SMM_Save_Game_Config;                              // 0x0398(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          SyncWithMissionSelector;                           // 0x03A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A1[0x7];                                      // 0x03A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 LobbyLevelData;                                    // 0x03A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 levelListname;                                     // 0x03B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 levelListnameModded;                               // 0x03C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<struct FGameplayTag>                   Difficulties;                                      // 0x03D8(0x0010)(Edit, BlueprintVisible)
	TMap<struct FGameplayTag, class FText>        Texts;                                             // 0x03E8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BndEvt__BPW_SMM_Page_LevelSelector_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_Page_LevelSelector_Button_Refresh_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__BPW_SMM_Page_LevelSelector_ComboBoxString_Difficulty_K2Node_ComponentBoundEvent_4_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void BndEvt__BPW_SMM_Page_LevelSelector_ListView_EntryPoints_K2Node_ComponentBoundEvent_2_OnListItemSelectionChangedDynamic__DelegateSignature(class UObject* Item, bool bIsSelected);
	void CamelToSentence(const class FString& In, class FString* Out);
	void CampaignButtonSelected(class UBPW_SMM_LevelSelector_CampaignButton_C* CampaignWidget);
	void Construct();
	void CreateCampaigns();
	void CreateLevels(class UBPW_SMM_LevelSelector_CampaignButton_C* CampaignButton, TMap<class FString, struct FLevelDataLookupTable>& LevelData);
	void CreateModLevels(class UBPW_SMM_LevelSelector_CampaignButton_C* CampaignButton);
	void DLCverify();
	class UWidget* DoCustomNavigation(EUINavigation Navigation_0);
	class UWidget* DoCustomNavigation_0(EUINavigation Navigation_0);
	void ExecuteUbergraph_BPW_SMM_Page_LevelSelector(int32 EntryPoint);
	void FixAspect();
	bool GetDLCsafe(const EGameVersionRestriction Key);
	class FText LevelFileNameClean(const class FString& InString);
	void LobbyMissionSelect(const class FString& URL, class FName Mode, class FName Entry);
	void Localize(const class FText& InText, class FText* OutText);
	void LogUpdated();
	void ModMenuPostInit(const TScriptInterface<class IBPI_SMM_UI_C> SMM_UI_0);
	void OnEntryObjectSelected(class UObject_SMM_LevelSelector_EntryPoint_C* Object);
	void OnMissionSelected_Delegate_Event();
	void OnRetrievedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame_Config);
	void OnSavedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame);
	void OnSelectLevel(class UBPW_SMM_LevelSelector_LevelButton_C* LevelButton);
	void OnUpdated_Event();
	void PageClosed();
	void PageOpened();
	void PreConstruct(bool IsDesignTime);
	void RefreshCampaigns();
	void SaveLoaded();
	void SendTabButton(class UButton* Button);
	void SetNavigationFocus(class UWidget** Widget);
	void SetupDifficulty();
	void UpdatedDifficulty();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_SMM_Page_LevelSelector_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_SMM_Page_LevelSelector_C")
	}
	static class UBPW_SMM_Page_LevelSelector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_SMM_Page_LevelSelector_C>();
	}
};
DUMPER7_ASSERTS_UBPW_SMM_Page_LevelSelector_C;

}

