#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_ConfigPLE

#include "Basic.hpp"

#include "BPW_Config_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_ConfigPLE.BPW_ConfigPLE_C
// 0x0020 (0x0368 - 0x0348)
class UBPW_ConfigPLE_C final : public UBPW_Config_Base_C
{
public:
	class UHorizontalBox*                         HorizontalBox_Main;                                // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_0;                                       // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_SMM_Setting_Bool_C*                  W_SMM_Setting_BoolPlayerLimitOverride;             // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_SMM_Setting_Integer_C*               W_SMM_Setting_Integerplayerlimit;                  // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetNavigationFocus(class UWidget** Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_ConfigPLE_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_ConfigPLE_C")
	}
	static class UBPW_ConfigPLE_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_ConfigPLE_C>();
	}
};
DUMPER7_ASSERTS_UBPW_ConfigPLE_C;

}

