#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SMM_Page_Settings

#include "Basic.hpp"

#include "BPW_SMM_Page_Settings_classes.hpp"
#include "BPW_SMM_Page_Settings_parameters.hpp"


namespace SDK
{

// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.ExecuteUbergraph_BPW_SMM_Page_Settings
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Page_Settings_C::ExecuteUbergraph_BPW_SMM_Page_Settings(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "ExecuteUbergraph_BPW_SMM_Page_Settings");

	Params::BPW_SMM_Page_Settings_C_ExecuteUbergraph_BPW_SMM_Page_Settings Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.InitilizeSettingPageTab
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBPS_SMM_SettingPageInfo&  SettingPageInfo                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBPW_SMM_Page_Settings_C::InitilizeSettingPageTab(const struct FBPS_SMM_SettingPageInfo& SettingPageInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "InitilizeSettingPageTab");

	Params::BPW_SMM_Page_Settings_C_InitilizeSettingPageTab Parms{};

	Parms.SettingPageInfo = std::move(SettingPageInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.Localize
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText*                            OutText                                                (Parm, OutParm)

void UBPW_SMM_Page_Settings_C::Localize(const class FText& InText, class FText* OutText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "Localize");

	Params::BPW_SMM_Page_Settings_C_Localize Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);

	if (OutText != nullptr)
		*OutText = std::move(Parms.OutText);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.LogUpdated
// (Public, BlueprintCallable, BlueprintEvent)

void UBPW_SMM_Page_Settings_C::LogUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "LogUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.ModMenuPostInit
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TScriptInterface<class IBPI_SMM_UI_C>SMM_UI_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Page_Settings_C::ModMenuPostInit(const TScriptInterface<class IBPI_SMM_UI_C> SMM_UI_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "ModMenuPostInit");

	Params::BPW_SMM_Page_Settings_C_ModMenuPostInit Parms{};

	Parms.SMM_UI_0 = SMM_UI_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.OnRetrievedSG
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ModName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    SlotName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class USMM_SaveGame_Base_C*             SMM_SaveGame_Config                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Page_Settings_C::OnRetrievedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame_Config)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "OnRetrievedSG");

	Params::BPW_SMM_Page_Settings_C_OnRetrievedSG Parms{};

	Parms.ModName = std::move(ModName);
	Parms.SlotName = std::move(SlotName);
	Parms.SMM_SaveGame_Config = SMM_SaveGame_Config;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.OnSavedSG
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ModName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    SlotName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class USMM_SaveGame_Base_C*             SMM_SaveGame                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Page_Settings_C::OnSavedSG(const class FString& ModName, const class FString& SlotName, class USMM_SaveGame_Base_C* SMM_SaveGame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "OnSavedSG");

	Params::BPW_SMM_Page_Settings_C_OnSavedSG Parms{};

	Parms.ModName = std::move(ModName);
	Parms.SlotName = std::move(SlotName);
	Parms.SMM_SaveGame = SMM_SaveGame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.PageClosed
// (Public, BlueprintCallable, BlueprintEvent)

void UBPW_SMM_Page_Settings_C::PageClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "PageClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.PageOpened
// (Public, BlueprintCallable, BlueprintEvent)

void UBPW_SMM_Page_Settings_C::PageOpened()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "PageOpened");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.PostInitTabs
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBPW_SMM_Page_Settings_C::PostInitTabs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "PostInitTabs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.SendTabButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UButton*                          Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Page_Settings_C::SendTabButton(class UButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "SendTabButton");

	Params::BPW_SMM_Page_Settings_C_SendTabButton Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.SetNavigationFocus
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget**                         Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Page_Settings_C::SetNavigationFocus(class UWidget** Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "SetNavigationFocus");

	Params::BPW_SMM_Page_Settings_C_SetNavigationFocus Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}


// Function BPW_SMM_Page_Settings.BPW_SMM_Page_Settings_C.TabSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBPW_SMM_TabSetting_C*            SettingTabWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    Keyboard                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_SMM_Page_Settings_C::TabSelected(class UBPW_SMM_TabSetting_C* SettingTabWidget, bool Keyboard)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_SMM_Page_Settings_C", "TabSelected");

	Params::BPW_SMM_Page_Settings_C_TabSelected Parms{};

	Parms.SettingTabWidget = SettingTabWidget;
	Parms.Keyboard = Keyboard;

	UObject::ProcessEvent(Func, &Parms);
}

}

