#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_ConfigLOG

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BPW_Config_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_ConfigLOG.BPW_ConfigLOG_C
// 0x0030 (0x0378 - 0x0348)
class UBPW_ConfigLOG_C final : public UBPW_Config_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BPW_ConfigLOG_C;                    // 0x0348(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UEditableTextBox*                       EditableTextBox_Console;                           // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_Main;                                // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMultiLineEditableTextBox*              MultiLineEditableTextBox_Log;                      // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_0;                                       // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_SMM_Setting_Bool_C*                  W_SMM_Setting_BoolconsoleLog;                      // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPW_ConfigLOG(int32 EntryPoint);
	void LogUpdated();
	void PostInitilizeMenus();
	void SetNavigationFocus(class UWidget** Widget);
	void UpdateLog();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPW_ConfigLOG_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPW_ConfigLOG_C")
	}
	static class UBPW_ConfigLOG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_ConfigLOG_C>();
	}
};
DUMPER7_ASSERTS_UBPW_ConfigLOG_C;

}

