#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModActor

#include "Basic.hpp"

#include "ModActor_classes.hpp"
#include "ModActor_parameters.hpp"


namespace SDK
{

// Function ModActor.ModActor_C.CheckForPawn_Event
// (BlueprintCallable, BlueprintEvent)

void AModActor_C::CheckForPawn_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ModActor_C", "CheckForPawn_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ModActor.ModActor_C.ExecuteUbergraph_ModActor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AModActor_C::ExecuteUbergraph_ModActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ModActor_C", "ExecuteUbergraph_ModActor");

	Params::ModActor_C_ExecuteUbergraph_ModActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ModActor.ModActor_C.InitializeVariables
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABasePlayer_C*                    Base_Player                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AModActor_C::InitializeVariables(class ABasePlayer_C* Base_Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ModActor_C", "InitializeVariables");

	Params::ModActor_C_InitializeVariables Parms{};

	Parms.Base_Player = Base_Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ModActor.ModActor_C.OnPossessedPawnChanged_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            OldPawn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class APawn*                            NewPawn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AModActor_C::OnPossessedPawnChanged_Event(class APawn* OldPawn, class APawn* NewPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ModActor_C", "OnPossessedPawnChanged_Event");

	Params::ModActor_C_OnPossessedPawnChanged_Event Parms{};

	Parms.OldPawn = OldPawn;
	Parms.NewPawn = NewPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ModActor.ModActor_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AModActor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ModActor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ModActor.ModActor_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AModActor_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ModActor_C", "ReceiveTick");

	Params::ModActor_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

