#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Object_SMM_LevelSelector_EntryPoint

#include "Basic.hpp"

#include "ReadyOrNot_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Object_SMM_LevelSelector_EntryPoint.Object_SMM_LevelSelector_EntryPoint_C
// 0x00B8 (0x00E0 - 0x0028)
class UObject_SMM_LevelSelector_EntryPoint_C final : public UObject
{
public:
	struct FEntryPoint                            EntryPoint;                                        // 0x0028(0x00A8)(Edit, BlueprintVisible, ExposeOnSpawn)
	TMulticastInlineDelegate<void(class UObject_SMM_LevelSelector_EntryPoint_C* Object)> OnSelected; // 0x00D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Object_SMM_LevelSelector_EntryPoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Object_SMM_LevelSelector_EntryPoint_C")
	}
	static class UObject_SMM_LevelSelector_EntryPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UObject_SMM_LevelSelector_EntryPoint_C>();
	}
};
DUMPER7_ASSERTS_UObject_SMM_LevelSelector_EntryPoint_C;

}

