#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PDA_SMM_MenuData

#include "Basic.hpp"

#include "BPS_SMM_PageInfo_structs.hpp"
#include "BPS_SMM_SettingPageInfo_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PDA_SMM_MenuData.PDA_SMM_MenuData_C
// 0x0070 (0x00A0 - 0x0030)
class UPDA_SMM_MenuData_C final : public UPrimaryDataAsset
{
public:
	TArray<struct FBPS_SMM_PageInfo>              WidgetWindows;                                     // 0x0030(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FBPS_SMM_SettingPageInfo>       WidgetSettings;                                    // 0x0040(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<TSoftClassPtr<class UClass>, int32>      WidgetTopButtons;                                  // 0x0050(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PDA_SMM_MenuData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PDA_SMM_MenuData_C")
	}
	static class UPDA_SMM_MenuData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPDA_SMM_MenuData_C>();
	}
};
DUMPER7_ASSERTS_UPDA_SMM_MenuData_C;

}

