#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SMM_AsyncLoadSave

#include "Basic.hpp"

#include "SMM_AsyncLoadSave_classes.hpp"
#include "SMM_AsyncLoadSave_parameters.hpp"


namespace SDK
{

// Function SMM_AsyncLoadSave.SMM_AsyncLoadSave_C.AsyncLoadSave
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ModName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    SlotName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// TSoftClassPtr<class UClass>             Class_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// class UUserWidget*                      Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void USMM_AsyncLoadSave_C::AsyncLoadSave(const class FString& ModName, const class FString& SlotName, TSoftClassPtr<class UClass> Class_0, class UUserWidget* Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SMM_AsyncLoadSave_C", "AsyncLoadSave");

	Params::SMM_AsyncLoadSave_C_AsyncLoadSave Parms{};

	Parms.ModName = std::move(ModName);
	Parms.SlotName = std::move(SlotName);
	Parms.Class_0 = Class_0;
	Parms.Context = Context;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SMM_AsyncLoadSave.SMM_AsyncLoadSave_C.Completed_99A4412447D90FF26FD045A8AB4CBCF4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class USaveGame*                        SaveGame                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bSuccess                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USMM_AsyncLoadSave_C::Completed_99A4412447D90FF26FD045A8AB4CBCF4(class USaveGame* SaveGame, bool bSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SMM_AsyncLoadSave_C", "Completed_99A4412447D90FF26FD045A8AB4CBCF4");

	Params::SMM_AsyncLoadSave_C_Completed_99A4412447D90FF26FD045A8AB4CBCF4 Parms{};

	Parms.SaveGame = SaveGame;
	Parms.bSuccess = bSuccess;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SMM_AsyncLoadSave.SMM_AsyncLoadSave_C.ExecuteUbergraph_SMM_AsyncLoadSave
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USMM_AsyncLoadSave_C::ExecuteUbergraph_SMM_AsyncLoadSave(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SMM_AsyncLoadSave_C", "ExecuteUbergraph_SMM_AsyncLoadSave");

	Params::SMM_AsyncLoadSave_C_ExecuteUbergraph_SMM_AsyncLoadSave Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

