#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SMM_SaveGame_Config_SMM

#include "Basic.hpp"

#include "SMM_SaveGame_Base_classes.hpp"
#include "ReadyOrNot_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass SMM_SaveGame_Config_SMM.SMM_SaveGame_Config_SMM_C
// 0x0020 (0x0498 - 0x0478)
class USMM_SaveGame_Config_SMM_C final : public USMM_SaveGame_Base_C
{
public:
	TArray<class FString>                         consoleCommands;                                   // 0x0478(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<EGameVersionRestriction>               ownedDLCs;                                         // 0x0488(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SMM_SaveGame_Config_SMM_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SMM_SaveGame_Config_SMM_C")
	}
	static class USMM_SaveGame_Config_SMM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USMM_SaveGame_Config_SMM_C>();
	}
};
DUMPER7_ASSERTS_USMM_SaveGame_Config_SMM_C;

}

