#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SMM_SaveGame_Config_PlayerLimit

#include "Basic.hpp"

#include "SMM_SaveGame_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SMM_SaveGame_Config_PlayerLimit.SMM_SaveGame_Config_PlayerLimit_C
// 0x0000 (0x0478 - 0x0478)
class USMM_SaveGame_Config_PlayerLimit_C final : public USMM_SaveGame_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SMM_SaveGame_Config_PlayerLimit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SMM_SaveGame_Config_PlayerLimit_C")
	}
	static class USMM_SaveGame_Config_PlayerLimit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USMM_SaveGame_Config_PlayerLimit_C>();
	}
};
DUMPER7_ASSERTS_USMM_SaveGame_Config_PlayerLimit_C;

}

