#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SMM_Setting_Rotator

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "W_SMM_Setting_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_SMM_Setting_Rotator.W_SMM_Setting_Rotator_C
// 0x12E0 (0x1670 - 0x0390)
class UW_SMM_Setting_Rotator_C final : public UW_SMM_Setting_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_W_SMM_Setting_Rotator_C;            // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UEditableText*                          EditableText_SettingTitle;                         // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_SpinBox_X;                                 // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_SpinBox_Y;                                 // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_SpinBox_Z;                                 // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_Float_X;                                   // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_Float_Y;                                   // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               SpinBox_Float_Z;                                   // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FRotator                               StartValue;                                        // 0x03D0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	TMulticastInlineDelegate<void(const struct FRotator& Value)> OnRotatorChanged;                   // 0x03E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FVector                                MinValue;                                          // 0x03F8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                MaxValue;                                          // 0x0410(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                MinSliderValue;                                    // 0x0428(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                MaxSliderValue;                                    // 0x0440(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Min_Fractional_Digits;                             // 0x0458(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Max_Fractional_Digits;                             // 0x045C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         In_Min_Desired_Width;                              // 0x0460(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         In_Max_Desired_Width;                              // 0x0464(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Delta;                                             // 0x0468(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Slider_Exponent;                                   // 0x046C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSpinBoxStyle                          Style_X;                                           // 0x0470(0x0600)(Edit, BlueprintVisible)
	struct FSpinBoxStyle                          Style_Y;                                           // 0x0A70(0x0600)(Edit, BlueprintVisible)
	struct FSpinBoxStyle                          Style_Z;                                           // 0x1070(0x0600)(Edit, BlueprintVisible)

public:
	void BndEvt__W_SMM_Setting_Float_SpinBox_Float_K2Node_ComponentBoundEvent_2_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__W_SMM_Setting_Rotator_SpinBox_Float_X_K2Node_ComponentBoundEvent_3_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__W_SMM_Setting_Rotator_SpinBox_Float_Y_K2Node_ComponentBoundEvent_4_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__W_SMM_Setting_Rotator_SpinBox_Float_Z_K2Node_ComponentBoundEvent_5_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
	void BndEvt__W_SMM_Setting_Vector_SpinBox_Float_Y_K2Node_ComponentBoundEvent_0_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__W_SMM_Setting_Vector_SpinBox_Float_Z_K2Node_ComponentBoundEvent_1_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void Construct();
	void ExecuteUbergraph_W_SMM_Setting_Rotator(int32 EntryPoint);
	void GetFloatFromVectorByIndex(const struct FVector& Vec, int32 int_0, double* Value);
	void GetRightSettingNavigation(class UWidget** Widget);
	void InitValueSMM(const TScriptInterface<class IBPI_SMM_UI_C>& SMM_UI);
	void LoadDefaults();
	void PreConstruct(bool IsDesignTime);
	void SetSpinBox(class USpinBox* InSpinBox, int32 Index_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_SMM_Setting_Rotator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_SMM_Setting_Rotator_C")
	}
	static class UW_SMM_Setting_Rotator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_SMM_Setting_Rotator_C>();
	}
};
DUMPER7_ASSERTS_UW_SMM_Setting_Rotator_C;

}

