#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SMM_Setting_Object

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function W_SMM_Setting_Object.W_SMM_Setting_Object_C.BndEvt__W_SMM_Setting_Name_EditableTextBox_SettingValue_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct W_SMM_Setting_Object_C_BndEvt__W_SMM_Setting_Name_EditableTextBox_SettingValue_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	ETextCommit                                   CommitMethod;                                      // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_SMM_Setting_Object_C_BndEvt__W_SMM_Setting_Name_EditableTextBox_SettingValue_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature;

// Function W_SMM_Setting_Object.W_SMM_Setting_Object_C.ExecuteUbergraph_W_SMM_Setting_Object
// 0x0288 (0x0288 - 0x0000)
struct W_SMM_Setting_Object_C_ExecuteUbergraph_W_SMM_Setting_Object final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_SMM_UI_C>         K2Node_Event_SMM_UI;                               // 0x0008(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Loc_OutText;                              // 0x0018(0x0018)()
	TSubclassOf<class UObject>                    CallFunc_Conv_SoftClassReferenceToClass_ReturnValue; // 0x0030(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsSMM_Save_Game_Base;      // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USMM_SaveGame_Base_C*                   CallFunc_BlockingRetrieveSG_SMM_SaveGame;          // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UObject>                 CallFunc_Map_Find_Value;                           // 0x0058(0x0028)(HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftObjectPath                        CallFunc_Conv_SoftObjRefToSoftObjPath_ReturnValue; // 0x0088(0x0020)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_BreakSoftObjectPath_PathString;           // 0x00A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TMap<class FName, TSoftObjectPtr<class UObject>> Temp_name_Variable;                             // 0x00B8(0x0050)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0108(0x0018)()
	TSoftObjectPtr<class UObject>                 CallFunc_Map_Find_Value_1;                         // 0x0120(0x0028)(HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftObjectPath                        CallFunc_Conv_SoftObjRefToSoftObjPath_ReturnValue_1; // 0x0150(0x0020)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_BreakSoftObjectPath_PathString_1;         // 0x0170(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0180(0x0018)()
	class FString                                 CallFunc_GetPrintValue_ReturnValue;                // 0x0198(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FSoftObjectPath                        CallFunc_Conv_SoftObjRefToSoftObjPath_ReturnValue_2; // 0x01A8(0x0020)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_BreakSoftObjectPath_PathString_2;         // 0x01C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x01D8(0x0018)()
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x01F0(0x0018)(ConstParm)
	ETextCommit                                   K2Node_ComponentBoundEvent_CommitMethod;           // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_209[0x7];                                      // 0x0209(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0210(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FSoftObjectPath                        CallFunc_MakeSoftObjectPath_ReturnValue;           // 0x0220(0x0020)(ZeroConstructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UObject>                 CallFunc_Conv_SoftObjPathToSoftObjRef_ReturnValue; // 0x0240(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	class FText                                   CallFunc_Loc_OutText_1;                            // 0x0268(0x0018)()
	class UWidget*                                CallFunc_GetRightSettingNavigation_Widget;         // 0x0280(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_SMM_Setting_Object_C_ExecuteUbergraph_W_SMM_Setting_Object;

// Function W_SMM_Setting_Object.W_SMM_Setting_Object_C.GetRightSettingNavigation
// 0x0008 (0x0008 - 0x0000)
struct W_SMM_Setting_Object_C_GetRightSettingNavigation final
{
public:
	class UWidget*                                Widget;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_SMM_Setting_Object_C_GetRightSettingNavigation;

// Function W_SMM_Setting_Object.W_SMM_Setting_Object_C.InitValueSMM
// 0x0010 (0x0010 - 0x0000)
struct W_SMM_Setting_Object_C_InitValueSMM final
{
public:
	TScriptInterface<class IBPI_SMM_UI_C>         SMM_UI;                                            // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_SMM_Setting_Object_C_InitValueSMM;

// Function W_SMM_Setting_Object.W_SMM_Setting_Object_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_SMM_Setting_Object_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_SMM_Setting_Object_C_PreConstruct;

}

