#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SMM_Setting_Bool

#include "Basic.hpp"


namespace SDK::Params
{

// Function W_SMM_Setting_Bool.W_SMM_Setting_Bool_C.BndEvt__W_SMM_Setting_Bool2_BPW_ToggleButton_K2Node_ComponentBoundEvent_1_OnBoolChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct W_SMM_Setting_Bool_C_BndEvt__W_SMM_Setting_Bool2_BPW_ToggleButton_K2Node_ComponentBoundEvent_1_OnBoolChanged__DelegateSignature final
{
public:
	bool                                          Value;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_SMM_Setting_Bool_C_BndEvt__W_SMM_Setting_Bool2_BPW_ToggleButton_K2Node_ComponentBoundEvent_1_OnBoolChanged__DelegateSignature;

// Function W_SMM_Setting_Bool.W_SMM_Setting_Bool_C.ExecuteUbergraph_W_SMM_Setting_Bool
// 0x0108 (0x0108 - 0x0000)
struct W_SMM_Setting_Bool_C_ExecuteUbergraph_W_SMM_Setting_Bool final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetRightSettingNavigation_Widget;         // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_Value;                  // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBPI_SMM_UI_C>         K2Node_Event_SMM_UI;                               // 0x0018(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UObject>                    CallFunc_Conv_SoftClassReferenceToClass_ReturnValue; // 0x0028(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsSMM_Save_Game_Base;      // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USMM_SaveGame_Base_C*                   CallFunc_BlockingRetrieveSG_SMM_SaveGame;          // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_Value;                           // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B[0x5];                                       // 0x004B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FName, bool>                       Temp_name_Variable;                                // 0x0050(0x0050)()
	class FString                                 CallFunc_Conv_BoolToString_ReturnValue;            // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_Value_1;                         // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_BoolToString_ReturnValue_1;          // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetPrintValue_ReturnValue;                // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Loc_OutText;                              // 0x00D8(0x0018)()
	class FText                                   CallFunc_Loc_OutText_1;                            // 0x00F0(0x0018)()
};
DUMPER7_ASSERTS_W_SMM_Setting_Bool_C_ExecuteUbergraph_W_SMM_Setting_Bool;

// Function W_SMM_Setting_Bool.W_SMM_Setting_Bool_C.GetRightSettingNavigation
// 0x0018 (0x0018 - 0x0000)
struct W_SMM_Setting_Bool_C_GetRightSettingNavigation final
{
public:
	class UWidget*                                Widget;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_Select_Default;                             // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_SMM_Setting_Bool_C_GetRightSettingNavigation;

// Function W_SMM_Setting_Bool.W_SMM_Setting_Bool_C.InitValueSMM
// 0x0010 (0x0010 - 0x0000)
struct W_SMM_Setting_Bool_C_InitValueSMM final
{
public:
	TScriptInterface<class IBPI_SMM_UI_C>         SMM_UI;                                            // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_SMM_Setting_Bool_C_InitValueSMM;

// Function W_SMM_Setting_Bool.W_SMM_Setting_Bool_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_SMM_Setting_Bool_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_SMM_Setting_Bool_C_PreConstruct;

}

