#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SMM_Setting_Bool

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "W_SMM_Setting_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_SMM_Setting_Bool.W_SMM_Setting_Bool_C
// 0x0030 (0x03C0 - 0x0390)
class UW_SMM_Setting_Bool_C final : public UW_SMM_Setting_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_W_SMM_Setting_Bool_C;               // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBPW_ToggleButton_C*                    BPW_ToggleButton;                                  // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableText*                          EditableText_SettingTitle;                         // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          StartValue;                                        // 0x03A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A9[0x7];                                      // 0x03A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(bool Value)>    OnBoolChanged;                                     // 0x03B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__W_SMM_Setting_Bool2_BPW_ToggleButton_K2Node_ComponentBoundEvent_0_AddedToFocusPath__DelegateSignature();
	void BndEvt__W_SMM_Setting_Bool2_BPW_ToggleButton_K2Node_ComponentBoundEvent_1_OnBoolChanged__DelegateSignature(bool Value);
	void ExecuteUbergraph_W_SMM_Setting_Bool(int32 EntryPoint);
	void GetRightSettingNavigation(class UWidget** Widget);
	void InitValueSMM(const TScriptInterface<class IBPI_SMM_UI_C>& SMM_UI);
	void LoadDefaults();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_SMM_Setting_Bool_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_SMM_Setting_Bool_C")
	}
	static class UW_SMM_Setting_Bool_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_SMM_Setting_Bool_C>();
	}
};
DUMPER7_ASSERTS_UW_SMM_Setting_Bool_C;

}

