#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SMM_Setting_Name

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "W_SMM_Setting_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_SMM_Setting_Name.W_SMM_Setting_Name_C
// 0x0040 (0x03D0 - 0x0390)
class UW_SMM_Setting_Name_C final : public UW_SMM_Setting_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_W_SMM_Setting_Name_C;               // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UEditableText*                          EditableText_SettingTitle;                         // 0x0398(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       EditableTextBox_SettingValue;                      // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_SpinBox;                                   // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FName                                   StartValue;                                        // 0x03B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class FName Value)> OnNameChanged;                                 // 0x03B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	float                                         In_Min_Desired_Width;                              // 0x03C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         In_Max_Desired_Width;                              // 0x03CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__W_SMM_Setting_Name_EditableTextBox_SettingValue_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void Construct();
	void ExecuteUbergraph_W_SMM_Setting_Name(int32 EntryPoint);
	void GetRightSettingNavigation(class UWidget** Widget);
	void InitValueSMM(const TScriptInterface<class IBPI_SMM_UI_C>& SMM_UI);
	void LoadDefaults();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_SMM_Setting_Name_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_SMM_Setting_Name_C")
	}
	static class UW_SMM_Setting_Name_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_SMM_Setting_Name_C>();
	}
};
DUMPER7_ASSERTS_UW_SMM_Setting_Name_C;

}

