#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SMM_Setting_Integer

#include "Basic.hpp"

#include "W_SMM_Setting_Integer_classes.hpp"
#include "W_SMM_Setting_Integer_parameters.hpp"


namespace SDK
{

// Function W_SMM_Setting_Integer.W_SMM_Setting_Integer_C.BndEvt__W_SMM_Setting_Float_SpinBox_Float_K2Node_ComponentBoundEvent_0_OnSpinBoxValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   InValue                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_Integer_C::BndEvt__W_SMM_Setting_Float_SpinBox_Float_K2Node_ComponentBoundEvent_0_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_Integer_C", "BndEvt__W_SMM_Setting_Float_SpinBox_Float_K2Node_ComponentBoundEvent_0_OnSpinBoxValueChangedEvent__DelegateSignature");

	Params::W_SMM_Setting_Integer_C_BndEvt__W_SMM_Setting_Float_SpinBox_Float_K2Node_ComponentBoundEvent_0_OnSpinBoxValueChangedEvent__DelegateSignature Parms{};

	Parms.InValue = InValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SMM_Setting_Integer.W_SMM_Setting_Integer_C.BndEvt__W_SMM_Setting_Float_SpinBox_Float_K2Node_ComponentBoundEvent_2_OnSpinBoxValueCommittedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   InValue                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_Integer_C::BndEvt__W_SMM_Setting_Float_SpinBox_Float_K2Node_ComponentBoundEvent_2_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_Integer_C", "BndEvt__W_SMM_Setting_Float_SpinBox_Float_K2Node_ComponentBoundEvent_2_OnSpinBoxValueCommittedEvent__DelegateSignature");

	Params::W_SMM_Setting_Integer_C_BndEvt__W_SMM_Setting_Float_SpinBox_Float_K2Node_ComponentBoundEvent_2_OnSpinBoxValueCommittedEvent__DelegateSignature Parms{};

	Parms.InValue = InValue;
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SMM_Setting_Integer.W_SMM_Setting_Integer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_SMM_Setting_Integer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_Integer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SMM_Setting_Integer.W_SMM_Setting_Integer_C.ExecuteUbergraph_W_SMM_Setting_Integer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_Integer_C::ExecuteUbergraph_W_SMM_Setting_Integer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_Integer_C", "ExecuteUbergraph_W_SMM_Setting_Integer");

	Params::W_SMM_Setting_Integer_C_ExecuteUbergraph_W_SMM_Setting_Integer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SMM_Setting_Integer.W_SMM_Setting_Integer_C.GetRightSettingNavigation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget**                         Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_Integer_C::GetRightSettingNavigation(class UWidget** Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_Integer_C", "GetRightSettingNavigation");

	Params::W_SMM_Setting_Integer_C_GetRightSettingNavigation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}


// Function W_SMM_Setting_Integer.W_SMM_Setting_Integer_C.InitValueSMM
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TScriptInterface<class IBPI_SMM_UI_C>&SMM_UI                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_Integer_C::InitValueSMM(const TScriptInterface<class IBPI_SMM_UI_C>& SMM_UI)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_Integer_C", "InitValueSMM");

	Params::W_SMM_Setting_Integer_C_InitValueSMM Parms{};

	Parms.SMM_UI = SMM_UI;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SMM_Setting_Integer.W_SMM_Setting_Integer_C.LoadDefaults
// (BlueprintCallable, BlueprintEvent)

void UW_SMM_Setting_Integer_C::LoadDefaults()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_Integer_C", "LoadDefaults");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SMM_Setting_Integer.W_SMM_Setting_Integer_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_Integer_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_Integer_C", "PreConstruct");

	Params::W_SMM_Setting_Integer_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

