#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SMM_Setting_StringSelector

#include "Basic.hpp"

#include "W_SMM_Setting_StringSelector_classes.hpp"
#include "W_SMM_Setting_StringSelector_parameters.hpp"


namespace SDK
{

// Function W_SMM_Setting_StringSelector.W_SMM_Setting_StringSelector_C.BndEvt__W_SMM_Setting_StringSelector_ComboBoxString_Value_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    SelectedItem                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// ESelectInfo                             SelectionType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_StringSelector_C::BndEvt__W_SMM_Setting_StringSelector_ComboBoxString_Value_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_StringSelector_C", "BndEvt__W_SMM_Setting_StringSelector_ComboBoxString_Value_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature");

	Params::W_SMM_Setting_StringSelector_C_BndEvt__W_SMM_Setting_StringSelector_ComboBoxString_Value_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature Parms{};

	Parms.SelectedItem = std::move(SelectedItem);
	Parms.SelectionType = SelectionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SMM_Setting_StringSelector.W_SMM_Setting_StringSelector_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_SMM_Setting_StringSelector_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_StringSelector_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SMM_Setting_StringSelector.W_SMM_Setting_StringSelector_C.ExecuteUbergraph_W_SMM_Setting_StringSelector
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_StringSelector_C::ExecuteUbergraph_W_SMM_Setting_StringSelector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_StringSelector_C", "ExecuteUbergraph_W_SMM_Setting_StringSelector");

	Params::W_SMM_Setting_StringSelector_C_ExecuteUbergraph_W_SMM_Setting_StringSelector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SMM_Setting_StringSelector.W_SMM_Setting_StringSelector_C.GetRightSettingNavigation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget**                         Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_StringSelector_C::GetRightSettingNavigation(class UWidget** Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_StringSelector_C", "GetRightSettingNavigation");

	Params::W_SMM_Setting_StringSelector_C_GetRightSettingNavigation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}


// Function W_SMM_Setting_StringSelector.W_SMM_Setting_StringSelector_C.InitValueSMM
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TScriptInterface<class IBPI_SMM_UI_C>&SMM_UI                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_StringSelector_C::InitValueSMM(const TScriptInterface<class IBPI_SMM_UI_C>& SMM_UI)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_StringSelector_C", "InitValueSMM");

	Params::W_SMM_Setting_StringSelector_C_InitValueSMM Parms{};

	Parms.SMM_UI = SMM_UI;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_SMM_Setting_StringSelector.W_SMM_Setting_StringSelector_C.LoadDefaults
// (BlueprintCallable, BlueprintEvent)

void UW_SMM_Setting_StringSelector_C::LoadDefaults()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_StringSelector_C", "LoadDefaults");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_SMM_Setting_StringSelector.W_SMM_Setting_StringSelector_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_SMM_Setting_StringSelector_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SMM_Setting_StringSelector_C", "PreConstruct");

	Params::W_SMM_Setting_StringSelector_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

